version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8080:8080'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
  db:
    image: postgres:11.5
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
